#!/bin/bash
# install_boost

build_dir=/mnt/sdb/source
boost_ver=${1:-boost_1_54_0}
ver_number=${boost_ver//boost_/}
tarball_name=${boost_ver}.tar.bz2
install_dir=/usr/local/${boost_ver}
boost_ld_conf=/etc/ld.so.conf.d/boost.conf
download_link=http://sourceforge.net/projects/boost/files/boost

mkdir -p ${build_dir} ${install_dir}
cd ${build_dir}
wget ${download_link}/${ver_number//_/.}/${tarball_name}
tar -xf ${tarball_name}

cd ${boost_ver}
${build_dir}/${boost_ver}/bootstrap.sh --prefix=${install_dir}
./b2 --build-type=complete --layout=versioned
./b2 install

cd ${install_dir}/lib
ls -1 | awk '/[0-9]$/' | xargs -i strip {}

rm -rf ${build_dir}
yum -y remove $(rpm -qa | grep boost)

echo ${install_dir}/lib >> ${boost_ld_conf}
ldconfig
