#!/bin/bash
# install_go

cat << \EOF >> /etc/profile
export GOROOT=/usr/local/go
export GOBIN=${GOROOT}/bin
export GOOS=linux
export GOARCH=amd64
export GOMAXPROCS=1
export GOPATH=/usr/local/go_library
export PATH=${GOBIN}:${GOPATH}:${GOROOT}/pkg/tool/linux_amd64:${PATH}
EOF

cat << \EOF >> ${HOME}/.bashrc
if ! pidof godoc &> /dev/null; then
     godoc -play=true -http=:80 &
fi
EOF

source /etc/profile
mkdir -p ${GOPATH} ${GOROOT}
hg clone -u release https://go.googlecode.com/hg/ ${GOROOT}
cd ${GOROOT}/src
./all.bash

path=${GOROOT}/misc/vim
echo "syntax on" >> ${HOME}/.vimrc
mkdir -p ${HOME}/.vim/{ftdetect,syntax,autoload/go}
ln -s ${path}/syntax/go.vim ${HOME}/.vim/syntax
ln -s ${path}/ftdetect/gofiletype.vim ${HOME}/.vim/ftdetect
ln -s ${path}/autoload/go/complete.vim ${HOME}/.vim/autoload/go
